### ISSUE TITLE
"Multiple auth mechanisms are not allowed" error

### ISSUE THREAD

**Issue by per1234** [MrOctopus/download-asset-action#1]
Previously working workflows using `MrOctopus/download-asset-action` steps have started failing sometime in the last week with this error:

```
Error: <Error><Code>AccessDenied</Code><Message>Multiple auth mechanisms are not allowed; please use either query parameters or an Authorization header</Message><Resource>github-production-release-asset-2e65be</Resource></Error>
```

It is not a universal breakage though. For example, this is failing:
```yaml
- uses: MrOctopus/download-asset-action@main
  with:
    repository: fireundubh/pyro
    asset: pyro
```

but this one is not:
```yaml
- uses: MrOctopus/download-asset-action@main
  with:
    repository: microsoft/DirectXTex
    asset: texconv
```

That gave me an idea it might be the difference between repos owned by an organization vs individual, but the same issue also occurs for some organization repos.

It looks like @devkanro and @MrTolerant may have been working on the issue. Maybe they have some insights?
